UKRAINE_ID = {
    4915: {'en': 'Ukraine', 'uk': 'Україна'},
}
OBLAST_IDS = {
    105: {'en': 'Vinnytsia', 'uk': 'Вінницька область'},
    107: {'en': 'Volynska', 'uk': 'Волинська область'},
    112: {'en': 'Dnipropetrovska', 'uk': 'Дніпропетровська область'},
    114: {'en': 'Donetska', 'uk': 'Донецька область'},
    118: {'en': 'Zhytomyrskа', 'uk': 'Житомирська область'},
    121: {'en': 'Zakarpatska', 'uk': 'Закарпатська область'},
    123: {'en': 'Zaporizka', 'uk': 'Запорізька область'},
    126: {'en': 'Ivano-Frankivska', 'uk': 'Івано-Франківська область'},
    132: {'en': 'Kyivska', 'uk': 'Київська область'},
    135: {'en': 'Kirovohradska', 'uk': 'Кіровоградська область'},
    144: {'en': 'Luhanska', 'uk': 'Луганська область'},
    146: {'en': 'Lvivska', 'uk': 'Львівська область'},
    148: {'en': 'Mykolaivska', 'uk': 'Миколаївська область'},
    151: {'en': 'Odeska', 'uk': 'Одеська область'},
    153: {'en': 'Poltavska', 'uk': 'Полтавська область'},
    156: {'en': 'Rivnenska', 'uk': 'Рівненська область'},
    159: {'en': 'Sumska', 'uk': 'Сумська область'},
    161: {'en': 'Ternopilska', 'uk': 'Тернопільська область'},
    163: {'en': 'Kharkivska', 'uk': 'Харківська область'},
    165: {'en': 'Khersonska', 'uk': 'Херсонська область'},
    168: {'en': 'Khmelnytska', 'uk': 'Хмельницька область'},
    171: {'en': 'Cherkaska', 'uk': 'Черкаська область'},
    173: {'en': 'Chernivetska', 'uk': 'Чернівецька область'},
    174: {'en': 'Chernihivska', 'uk': 'Чернігівська область'},
    180: {'en': 'Kyiv', 'uk': 'м. Київ'},
}

COUNTRY_IDS = {
    32752: {'en': 'Afghanistan', 'uk': 'Афганістан'},
    32753: {'en': 'Albania', 'uk': 'Албанія'},
    32754: {'en': 'Algeria', 'uk': 'Алжир'},
    32755: {'en': 'Andorra', 'uk': 'Андорра'},
    32756: {'en': 'Angola', 'uk': 'Ангола'},
    32757: {'en': 'Antigua and Barbuda', 'uk': 'Антигуа та Барбуда'},
    32758: {'en': 'Argentina', 'uk': 'Аргентина'},
    32759: {'en': 'Armenia', 'uk': 'Вірменія'},
    32767: {'en': 'Australia', 'uk': 'Австралія'},
    32768: {'en': 'Austria', 'uk': 'Австрія'},
    32769: {'en': 'Azerbaijan', 'uk': 'Азербайджан'},
    32770: {'en': 'Bahamas', 'uk': 'Багами'},
    32771: {'en': 'Bahrain', 'uk': 'Бахрейн'},
    32772: {'en': 'Bangladesh', 'uk': 'Бангладеш'},
    32773: {'en': 'Barbados', 'uk': 'Барбадос'},
    32774: {'en': 'Belarus', 'uk': 'Білорусь'},
    32775: {'en': 'Belgium', 'uk': 'Бельгія'},
    32776: {'en': 'Benin', 'uk': 'Бенін'},
    32777: {'en': 'Bhutan', 'uk': 'Бутан'},
    32778: {'en': 'Bolivia', 'uk': 'Болівія'},
    32779: {'en': 'Bosnia and Herzegovina', 'uk': 'Боснія і Герцеговина'},
    32780: {'en': 'Brazil', 'uk': 'Бразилія'},
    32781: {'en': 'Brunei', 'uk': 'Бруней'},
    32782: {'en': 'Bulgaria', 'uk': 'Болгарія'},
    32783: {'en': 'Burkina Faso', 'uk': 'Буркіна-Фасо'},
    32784: {'en': 'Cabo Verde', 'uk': 'Кабо Верде'},
    32785: {'en': 'Cambodia', 'uk': 'Камбоджа'},
    32786: {'en': 'Cameroon', 'uk': 'Камерун'},
    32798: {'en': 'Central African Republic', 'uk': 'ЦАР'},
    32799: {'en': 'Chad', 'uk': 'Чад'},
    32800: {'en': 'Chile', 'uk': 'Чилі'},
    32833: {'en': 'China', 'uk': 'Китай'},
    32834: {'en': 'Colombia', 'uk': 'Колумбія'},
    32835: {'en': 'Congo (Brazzaville)', 'uk': 'Конго (Браззавіль)'},
    32836: {'en': 'Congo (Kinshasa)', 'uk': 'Конго (Кіншаса)'},
    32837: {'en': 'Costa Rica', 'uk': 'Коста-Ріка'},
    32838: {'en': "Cote d'Ivoire", 'uk': "Кот-д'Івуар"},
    32839: {'en': 'Croatia', 'uk': 'Хорватія'},
    32840: {'en': 'Diamond Princess', 'uk': 'Лайнер Diamond Princess'},
    32841: {'en': 'Cuba', 'uk': 'Куба'},
    32842: {'en': 'Cyprus', 'uk': 'Кіпр'},
    32843: {'en': 'Czechia', 'uk': 'Чехія'},
    32846: {'en': 'Denmark', 'uk': 'Данія'},
    32847: {'en': 'Djibouti', 'uk': 'Джибуті'},
    32848: {'en': 'Dominican Republic', 'uk': 'Домініканська республіка'},
    32849: {'en': 'Ecuador', 'uk': 'Еквадор'},
    32850: {'en': 'Egypt', 'uk': 'Єгипет'},
    32851: {'en': 'El Salvador', 'uk': 'Сальвадор'},
    32852: {'en': 'Equatorial Guinea', 'uk': 'Екваторіальна Гвінея'},
    32853: {'en': 'Eritrea', 'uk': 'Еритрея'},
    32854: {'en': 'Estonia', 'uk': 'Естонія'},
    32855: {'en': 'Eswatini', 'uk': 'Есватині'},
    32856: {'en': 'Ethiopia', 'uk': 'Ефіопія'},
    32857: {'en': 'Fiji', 'uk': 'Фіджі'},
    32858: {'en': 'Finland', 'uk': 'Фінляндія'},
    32869: {'en': 'Gabon', 'uk': 'Габон'},
    32870: {'en': 'Gambia', 'uk': 'Гамбія'},
    32871: {'en': 'Georgia', 'uk': 'Грузія'},
    32872: {'en': 'Germany', 'uk': 'Німеччина'},
    32873: {'en': 'Ghana', 'uk': 'Гана'},
    32874: {'en': 'Greece', 'uk': 'Греція'},
    32875: {'en': 'Guatemala', 'uk': 'Гватемала'},
    32876: {'en': 'Guinea', 'uk': 'Гвінея'},
    32877: {'en': 'Guyana', 'uk': 'Гайана'},
    32878: {'en': 'Haiti', 'uk': 'Гаїті'},
    32879: {'en': 'Holy See', 'uk': 'Ватикан'},
    32880: {'en': 'Honduras', 'uk': 'Гондурас'},
    32881: {'en': 'Hungary', 'uk': 'Угорщина'},
    32882: {'en': 'Iceland', 'uk': 'Ісландія'},
    32883: {'en': 'India', 'uk': 'Індія'},
    32884: {'en': 'Indonesia', 'uk': 'Індонезія'},
    32885: {'en': 'Iran', 'uk': 'Іран'},
    32886: {'en': 'Iraq', 'uk': 'Ірак'},
    32887: {'en': 'Ireland', 'uk': 'Ірландія'},
    32888: {'en': 'Israel', 'uk': 'Ізраїль'},
    32889: {'en': 'Italy', 'uk': 'Італія'},
    32890: {'en': 'Jamaica', 'uk': 'Ямайка'},
    32891: {'en': 'Japan', 'uk': 'Японія'},
    32892: {'en': 'Jordan', 'uk': 'Йорданія'},
    32893: {'en': 'Kazakhstan', 'uk': 'Казахстан'},
    32894: {'en': 'Kenya', 'uk': 'Кенія'},
    32895: {'en': 'Korea, South', 'uk': 'Південна Корея'},
    32896: {'en': 'Kuwait', 'uk': 'Кувейт'},
    32897: {'en': 'Kyrgyzstan', 'uk': 'Киргизстан'},
    32898: {'en': 'Latvia', 'uk': 'Латвія'},
    32899: {'en': 'Lebanon', 'uk': 'Ліван'},
    32900: {'en': 'Liberia', 'uk': 'Ліберія'},
    32901: {'en': 'Liechtenstein', 'uk': 'Ліхтенштейн'},
    32902: {'en': 'Lithuania', 'uk': 'Литва'},
    32903: {'en': 'Luxembourg', 'uk': 'Люксембург'},
    32904: {'en': 'Madagascar', 'uk': 'Мадагаскар'},
    32905: {'en': 'Malaysia', 'uk': 'Малайзія'},
    32906: {'en': 'Maldives', 'uk': 'Мальдіви'},
    32907: {'en': 'Malta', 'uk': 'Мальта'},
    32908: {'en': 'Mauritania', 'uk': 'Мавританія'},
    32909: {'en': 'Mauritius', 'uk': 'Маврикій'},
    32910: {'en': 'Mexico', 'uk': 'Мексика'},
    32911: {'en': 'Moldova', 'uk': 'Молдова'},
    32912: {'en': 'Monaco', 'uk': 'Монако'},
    32913: {'en': 'Mongolia', 'uk': 'Монголія'},
    32914: {'en': 'Montenegro', 'uk': 'Чорногорія'},
    32915: {'en': 'Morocco', 'uk': 'Марокко'},
    32916: {'en': 'Namibia', 'uk': 'Намібія'},
    32917: {'en': 'Nepal', 'uk': 'Непал'},
    32921: {'en': 'Netherlands', 'uk': 'Нідерланди'},
    32922: {'en': 'New Zealand', 'uk': 'Нова Зеландія'},
    32923: {'en': 'Nicaragua', 'uk': 'Нікарагуа'},
    32924: {'en': 'Niger', 'uk': 'Нігер'},
    32925: {'en': 'Nigeria', 'uk': 'Нігерія'},
    32926: {'en': 'North Macedonia', 'uk': 'Північна Македонія'},
    32927: {'en': 'Norway', 'uk': 'Норвегія'},
    32928: {'en': 'Oman', 'uk': 'Оман'},
    32929: {'en': 'Pakistan', 'uk': 'Пакистан'},
    32930: {'en': 'Panama', 'uk': 'Панама'},
    32931: {'en': 'Papua New Guinea', 'uk': 'Папуа-Нова Гвінея'},
    32932: {'en': 'Paraguay', 'uk': 'Парагвай'},
    32933: {'en': 'Peru', 'uk': 'Перу'},
    32934: {'en': 'Philippines', 'uk': 'Філіппіни'},
    32935: {'en': 'Poland', 'uk': 'Польща'},
    32936: {'en': 'Portugal', 'uk': 'Португалія'},
    32937: {'en': 'Qatar', 'uk': 'Катар'},
    32938: {'en': 'Romania', 'uk': 'Румунія'},
    32939: {'en': 'Russia', 'uk': 'Росія'},
    32940: {'en': 'Rwanda', 'uk': 'Руанда'},
    32941: {'en': 'Saint Lucia', 'uk': 'Сент-Люсія'},
    32942: {'en': 'Saint Vincent and the Grenadines', 'uk': 'Сент-Вінсент та Гренадини'},
    32943: {'en': 'San Marino', 'uk': 'Сан-Марино'},
    32944: {'en': 'Saudi Arabia', 'uk': 'Саудівська Аравія'},
    32945: {'en': 'Senegal', 'uk': 'Сенегал'},
    32946: {'en': 'Serbia', 'uk': 'Сербія'},
    32947: {'en': 'Seychelles', 'uk': 'Сейшельські острови'},
    32948: {'en': 'Singapore', 'uk': 'Сінгапур'},
    32949: {'en': 'Slovakia', 'uk': 'Словаччина'},
    32950: {'en': 'Slovenia', 'uk': 'Словенія'},
    32951: {'en': 'Somalia', 'uk': 'Сомалі'},
    32952: {'en': 'South Africa', 'uk': 'Південна Африка'},
    32953: {'en': 'Spain', 'uk': 'Іспанія'},
    32954: {'en': 'Sri Lanka', 'uk': 'Шрі Ланка'},
    32955: {'en': 'Sudan', 'uk': 'Судан'},
    32956: {'en': 'Suriname', 'uk': 'Сурінам'},
    32957: {'en': 'Sweden', 'uk': 'Швеція'},
    32958: {'en': 'Switzerland', 'uk': 'Швейцарія'},
    32959: {'en': 'Taiwan*', 'uk': 'Тайвань'},
    32960: {'en': 'Tanzania', 'uk': 'Танзанія'},
    32961: {'en': 'Thailand', 'uk': 'Таїланд'},
    32962: {'en': 'Togo', 'uk': 'Того'},
    32963: {'en': 'Trinidad and Tobago', 'uk': 'Тринідад і Тобаго'},
    32964: {'en': 'Tunisia', 'uk': 'Туніс'},
    32965: {'en': 'Turkey', 'uk': 'Туреччина'},
    32966: {'en': 'Uganda', 'uk': 'Уганда'},
    32967: {'en': 'United Arab Emirates', 'uk': "Об'єднані Арабські Емірати"},
    32974: {'en': 'United Kingdom', 'uk': 'Великобританія'},
    32975: {'en': 'Uruguay', 'uk': 'Уругвай'},
    32976: {'en': 'USA', 'uk': 'США'},
    32977: {'en': 'Uzbekistan', 'uk': 'Узбекистан'},
    32978: {'en': 'Venezuela', 'uk': 'Венесуела'},
    32979: {'en': 'Vietnam', 'uk': "В'єтнам"},
    32980: {'en': 'Zambia', 'uk': 'Замбія'},
    32981: {'en': 'Zimbabwe', 'uk': 'Зімбабве'},
    32983: {'en': 'Dominica', 'uk': 'Домініка'},
    32984: {'en': 'Grenada', 'uk': 'Гренада'},
    32985: {'en': 'Mozambique', 'uk': 'Мозамбік'},
    32986: {'en': 'Syria', 'uk': 'Сирія'},
    32987: {'en': 'Timor-Leste', 'uk': 'Тимор-Лешті'},
    32988: {'en': 'Belize', 'uk': 'Беліз'},
    32990: {'en': 'Laos', 'uk': 'Лаос'},
    32991: {'en': 'Libya', 'uk': 'Лівія'},
    32992: {'en': 'West Bank and Gaza', 'uk': 'Західний берег та Газа'},
    32993: {'en': 'Guinea-Bissau', 'uk': 'Гвінея-Бісау'},
    32994: {'en': 'Mali', 'uk': 'Малі'},
    32995: {'en': 'Saint Kitts and Nevis', 'uk': 'Сент-Кітс і Невіс'},
    32997: {'en': 'Canada', 'uk': 'Канада'},
    32998: {'en': 'Kosovo', 'uk': 'Косово'},
    32999: {'en': 'Burma', 'uk': 'Бірма'},
    33003: {'en': 'MS Zaandam', 'uk': 'Лайнер MS Zaandam'},
    33004: {'en': 'Botswana', 'uk': 'Ботсвана'},
    33313: {'en': 'Burundi', 'uk': 'Бурунді'},
    33315: {'en': 'Sierra Leone', 'uk': 'Сьєрра-Леоне'},
    33316: {'en': 'Malawi', 'uk': 'Малаві'},
    33578: {'en': 'South Sudan', 'uk': 'Півд. Судан'},
    33579: {'en': 'Western Sahara', 'uk': 'Західна Сахара'},
    33580: {'en': 'France', 'uk': 'Франція'},
    33582: {'en': 'Sao Tome and Principe', 'uk': 'Сан-Томе і Принсіпі'},
    35151: {'en': 'Yemen', 'uk': 'Ємен'},
    41201: {'en': 'Tajikistan', 'uk': 'Таджикистан'},
    41466: {'en': 'Comoros', 'uk': 'Коморські острови'},
    45707: {'en': 'Lesotho', 'uk': 'Лесото'},
}

COMBINED_IDS = {
    **OBLAST_IDS,
    **COUNTRY_IDS,
}
